/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Controls.java
 *
 * Created on 14.09.2010., 16.37.22
 */
package rs.etf.aor.gui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author MB
 */
public class Controls extends javax.swing.JPanel {

    private JFrame parent;

    /** Creates new form Controls */
    public Controls() {
        initComponents();
    }

    public Controls(JFrame parent) {
        this();
        this.parent = (MainWindow) parent;
    }

    public void setParent(JFrame parent) {
        this.parent = (MainWindow) parent;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel gettLabel() {
        return tLabel;
    }

    public JLabel getPcLabel() {
        return pcLabel;
    }

    public JTextArea getTextArea() {
        return jTextArea1;
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        clkButton = new javax.swing.JButton();
        insButton = new javax.swing.JButton();
        prgButton = new javax.swing.JButton();
        memButton = new javax.swing.JButton();
        regButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tLabel = new javax.swing.JLabel();
        pcLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(799, 110));
        setMinimumSize(new java.awt.Dimension(700, 110));
        setPreferredSize(new java.awt.Dimension(760, 110));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        clkButton.setText("CLK+");
        clkButton.setMaximumSize(new java.awt.Dimension(73, 23));
        clkButton.setMinimumSize(new java.awt.Dimension(73, 23));
        clkButton.setPreferredSize(new java.awt.Dimension(73, 23));
        clkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clkButtonActionPerformed(evt);
            }
        });

        insButton.setText("INS+");
        insButton.setMaximumSize(new java.awt.Dimension(73, 23));
        insButton.setMinimumSize(new java.awt.Dimension(73, 23));
        insButton.setPreferredSize(new java.awt.Dimension(73, 23));
        insButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insButtonActionPerformed(evt);
            }
        });

        prgButton.setText("PRG+");
        prgButton.setMaximumSize(new java.awt.Dimension(73, 23));
        prgButton.setMinimumSize(new java.awt.Dimension(73, 23));
        prgButton.setPreferredSize(new java.awt.Dimension(73, 23));
        prgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prgButtonActionPerformed(evt);
            }
        });

        memButton.setText("MEM");
        memButton.setMaximumSize(new java.awt.Dimension(73, 23));
        memButton.setMinimumSize(new java.awt.Dimension(73, 23));
        memButton.setPreferredSize(new java.awt.Dimension(73, 23));
        memButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memButtonActionPerformed(evt);
            }
        });

        regButton.setText("REG");
        regButton.setMaximumSize(new java.awt.Dimension(73, 23));
        regButton.setMinimumSize(new java.awt.Dimension(73, 23));
        regButton.setPreferredSize(new java.awt.Dimension(73, 23));
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });

        upButton.setText("UP");
        upButton.setMaximumSize(new java.awt.Dimension(73, 23));
        upButton.setMinimumSize(new java.awt.Dimension(73, 23));
        upButton.setPreferredSize(new java.awt.Dimension(73, 23));
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });

        loadButton.setText("LOAD");
        loadButton.setMaximumSize(new java.awt.Dimension(73, 23));
        loadButton.setMinimumSize(new java.awt.Dimension(73, 23));
        loadButton.setPreferredSize(new java.awt.Dimension(73, 23));
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        clearButton.setText("CLEAR");
        clearButton.setMaximumSize(new java.awt.Dimension(73, 23));
        clearButton.setMinimumSize(new java.awt.Dimension(73, 23));
        clearButton.setPreferredSize(new java.awt.Dimension(73, 23));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("PC =");

        jLabel2.setText("T = ");

        jLabel3.setText("Tclk = ");

        jLabel4.setText("0");

        tLabel.setText("0");

        pcLabel.setText("0x" + Integer.toHexString(CPU_blok_registri_cetvri.startPCValue));

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(pcLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(upButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(memButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prgButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clkButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pcLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clkButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prgButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void memButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memButtonActionPerformed
        MemoryDialog dialog = ((MainWindow) parent).getMemDialog();
        if (dialog == null) {
            dialog = new MemoryDialog(null, true, ((MainWindow) parent).getMemory());
        }
        else {
            dialog.refreshMemory(((MainWindow) parent).getMemory());
        }
        dialog.setVisible(true);
    }//GEN-LAST:event_memButtonActionPerformed

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        RegisterDialog regDialog = ((MainWindow) parent).getRegDialog();
        if (regDialog == null) {
            regDialog = new RegisterDialog(parent, ((MainWindow)parent).getMainPanel().getPC(),
                                           ((MainWindow)parent).getMainPanel().getA(),
                                           ((MainWindow)parent).getMainPanel().getB(),
                                           ((MainWindow)parent).getMainPanel().getIR1(),
                                           ((MainWindow)parent).getMainPanel().getIR2(),
                                           ((MainWindow)parent).getMainPanel().getIR3(),
                                           ((MainWindow)parent).getMainPanel().getIR4(),
                                           ((MainWindow)parent).getMainPanel().getMAR(),
                                           ((MainWindow)parent).getMainPanel().getMBR(),
                                           ((MainWindow)parent).getMainPanel().getRegX(),
                                           ((MainWindow)parent).getMainPanel().getRegY(),
                                           ((MainWindow)parent).getMainPanel().getIVTP(),
                                           ((MainWindow)parent).getMainPanel().getBR(),
                                           ((MainWindow)parent).getMainPanel().getAX(),
                                           ((MainWindow)parent).getMainPanel().getBX(),
                                           ((MainWindow)parent).getMainPanel().getCX(),
                                           ((MainWindow)parent).getMainPanel().getDX(),
                                           ((MainWindow)parent).getMainPanel().getSI(),
                                           ((MainWindow)parent).getMainPanel().getDI(),
                                           ((MainWindow)parent).getMainPanel().getSP(),
                                           ((MainWindow)parent).getMainPanel().getBP(),
                                           ((MainWindow)parent).getMainPanel().getSBUS(),
                                           ((MainWindow)parent).getMainPanel().getDBUS(),
                                           ((MainWindow)parent).getMainPanel().getSystemABUS(),
                                           ((MainWindow)parent).getMainPanel().getSystemDBUS(),
                                           ((MainWindow)parent).getMainPanel().getPSW());
        } else {
            regDialog.refreshValues(((MainWindow)parent).getMainPanel().getPC(),
                                    ((MainWindow)parent).getMainPanel().getA(),
                                    ((MainWindow)parent).getMainPanel().getB(),
                                    ((MainWindow)parent).getMainPanel().getIR1(),
                                    ((MainWindow)parent).getMainPanel().getIR2(),
                                    ((MainWindow)parent).getMainPanel().getIR3(),
                                    ((MainWindow)parent).getMainPanel().getIR4(),
                                    ((MainWindow)parent).getMainPanel().getMAR(),
                                    ((MainWindow)parent).getMainPanel().getMBR(),
                                    ((MainWindow)parent).getMainPanel().getRegX(),
                                    ((MainWindow)parent).getMainPanel().getRegY(),
                                    ((MainWindow)parent).getMainPanel().getIVTP(),
                                    ((MainWindow)parent).getMainPanel().getBR(),
                                    ((MainWindow)parent).getMainPanel().getAX(),
                                    ((MainWindow)parent).getMainPanel().getBX(),
                                    ((MainWindow)parent).getMainPanel().getCX(),
                                    ((MainWindow)parent).getMainPanel().getDX(),
                                    ((MainWindow)parent).getMainPanel().getSI(),
                                    ((MainWindow)parent).getMainPanel().getDI(),
                                    ((MainWindow)parent).getMainPanel().getSP(),
                                    ((MainWindow)parent).getMainPanel().getBP(),
                                    ((MainWindow)parent).getMainPanel().getSBUS(),
                                    ((MainWindow)parent).getMainPanel().getDBUS(),
                                    ((MainWindow)parent).getMainPanel().getSystemABUS(),
                                    ((MainWindow)parent).getMainPanel().getSystemDBUS(),
                                    ((MainWindow)parent).getMainPanel().getPSW());
        }
        regDialog.setVisible(true);
    }//GEN-LAST:event_regButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setMultiSelectionEnabled(false);
        int ret = chooser.showDialog(this, "Choose file...");

        if (ret == JFileChooser.CANCEL_OPTION) {
            return;
        }

        File choosedFile = chooser.getSelectedFile();
        byte[] code = rs.etf.aor.asm.Assembler.assemble(choosedFile);

        ((MainWindow) parent).loadProgram(code);

    }//GEN-LAST:event_loadButtonActionPerformed

    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
        ((MainWindow) parent).up();
    }//GEN-LAST:event_upButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        ((MainWindow) parent).clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void clkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clkButtonActionPerformed
        ((MainWindow) parent).clk();
    }//GEN-LAST:event_clkButtonActionPerformed

    private void insButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insButtonActionPerformed
        ((MainWindow) parent).inst();
    }//GEN-LAST:event_insButtonActionPerformed

    private void prgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prgButtonActionPerformed
        ((MainWindow) parent).prg();
    }//GEN-LAST:event_prgButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton clkButton;
    private javax.swing.JButton insButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton memButton;
    private javax.swing.JLabel pcLabel;
    private javax.swing.JButton prgButton;
    private javax.swing.JButton regButton;
    private javax.swing.JLabel tLabel;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables
}
