/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CPU_organizacija_interfejs.java
 *
 * Created on 22.09.2010., 10.26.20
 */

package rs.etf.aor.gui;

import java.awt.Graphics;
import java.awt.Point;
import javax.swing.JPanel;
import rs.etf.aor.components.Bus;
import rs.etf.aor.components.Junction;
import rs.etf.aor.components.Line;

/**
 *
 * @author MB
 */
public class CPU_organizacija_interfejs extends javax.swing.JPanel implements PanelsInfo{

    private JPanel parent;
    private String parentTitle = "CPU_organizacija_main";

    //components

    //lines
    Line lines[];

    //dots
    private Junction dot1, dot2;

    //bus
    Bus sbus, dbus, systemDBUS, systemABUS;


    /** Creates new form CPU_organizacija_interfejs */
    public CPU_organizacija_interfejs(JPanel parent) {
        this.parent = parent;
        initComponents();
        initPictureComponents();
        initLines();
        initBus();
        connectComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/etf/aor/images/CPU_organizacija_interfejs.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public String getParentTitle() {
        return parentTitle;
    }

    private void initLines() {
        lines = new Line[8];
        for(int i = 0; i<lines.length; i++){
            lines[i] = new Line(null, 0, 0, 1);
        }

        //RDBUS1
        lines[0].addPoint(new Point(566, 75));
        lines[0].addPoint(new Point(566, 159));

        //RDBUS2
        lines[1].addPoint(new Point(566, 159));
        lines[1].addPoint(new Point(566, 215));

        //RDBUS from CPU
        lines[2].addPoint(new Point(442, 159));
        lines[2].addPoint(new Point(565, 159));

        //WRBUS1
        lines[3].addPoint(new Point(585, 75));
        lines[3].addPoint(new Point(585, 141));

        //WRBUS2
        lines[4].addPoint(new Point(585, 141));
        lines[4].addPoint(new Point(585, 215));

        //WRBUS from CPU
        lines[5].addPoint(new Point(442, 141));
        lines[5].addPoint(new Point(584, 141));

        //WRBUS>
        lines[6].addPoint(new Point(577, 137));
        lines[6].addPoint(new Point(584, 141));
        lines[6].addPoint(new Point(577, 145));

        //RDBUS>
        lines[7].addPoint(new Point(558, 155));
        lines[7].addPoint(new Point(565, 159));
        lines[7].addPoint(new Point(558, 163));

    }

    private void initBus() {

        sbus = new Bus(16);
        dbus = new Bus(16);
        systemABUS = new Bus(16);
        systemDBUS = new Bus(8);

        sbus.addPoint(new Point(87, 74));
        sbus.addPoint(new Point(87, 231));
        sbus.addPoint(new Point(87, 166));
        sbus.addPoint(new Point(142, 166));

        dbus.addPoint(new Point(106, 74));
        dbus.addPoint(new Point(106, 231));
        dbus.addPoint(new Point(106, 188));
        dbus.addPoint(new Point(142, 188));

        systemDBUS.addPoint(new Point (480, 74));
        systemDBUS.addPoint(new Point (480, 231));
        systemDBUS.addPoint(new Point (444, 188));
        systemDBUS.addPoint(new Point (480, 188));

        systemABUS.addPoint(new Point (529, 74));
        systemABUS.addPoint(new Point (529, 231));
        systemABUS.addPoint(new Point (444, 173));
        systemABUS.addPoint(new Point (529, 173));

        sbus.addTextPoint(new Point(55, 90));
        dbus.addTextPoint(new Point(109, 90));
        systemDBUS.addTextPoint(new Point(483, 90));
        systemABUS.addTextPoint(new Point(532, 90));

    }

    private void initPictureComponents() {
        dot1 = new Junction(3);
        dot2 = new Junction(3);

    }

    private void connectComponents() {
        dot1.setLine(lines[0], 0);
        dot1.setLine(lines[1], 1);
        dot1.setLine(lines[7], 2);
        lines[2].setNextComp(dot1);

        dot2.setLine(lines[3], 0);
        dot2.setLine(lines[4], 1);
        dot2.setLine(lines[6], 2);
        lines[5].setNextComp(dot2);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        for (int i = 0; i < lines.length; i++) {
            lines[i].paint(g);
        }
        sbus.paint(g);
        dbus.paint(g);
        systemDBUS.paint(g);
        systemABUS.paint(g);
    }

    public void refreshSequential() {
    }

    public void clock() {
    }

    public void clear() {
    }

}
