/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CPU_organizacija_prekid.java
 *
 * Created on 22.09.2010., 13.49.21
 */

package rs.etf.aor.gui;

import java.awt.Graphics;
import java.awt.Point;
import javax.swing.JPanel;
import rs.etf.aor.components.Bus;

/**
 *
 * @author MB
 */
public class CPU_organizacija_prekid extends javax.swing.JPanel implements PanelsInfo{

    private JPanel parent;
    private String parentTitle = "CPU_organizacija_main";

    Bus sbus, dbus;

    /** Creates new form CPU_organizacija_prekid */
    public CPU_organizacija_prekid(JPanel parent) {
        this.parent = parent;
        initComponents();

        sbus = new Bus(16);
        dbus = new Bus(16);

        sbus.addPoint(new Point(216, 211));
        sbus.addPoint(new Point(422, 211));
        sbus.addPoint(new Point(368, 193));
        sbus.addPoint(new Point(368, 211));

        dbus.addPoint(new Point(216, 230));
        dbus.addPoint(new Point(422, 230));
        dbus.addPoint(new Point(244, 193));
        dbus.addPoint(new Point(244, 230));

        sbus.addTextPoint(new Point(210, 209));
        dbus.addTextPoint(new Point(210, 228));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/etf/aor/images/CPU_organizacija_prekid.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public String getParentTitle() {
        return parentTitle;
    }

    public void initLines() {
    }

    public void initPictureComponents() {
    }

    public void connectComponents() {
    }

    public void refreshSequential() {
    }

    public void clock() {
    }

    public void clear() {
    }

    @Override
    public void paint (Graphics g) {
        super.paint(g);
        sbus.paint(g);
        dbus.paint(g);
    }

}
