/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegisterDialog.java
 *
 * Created on 25.09.2010., 16.03.56
 */

package rs.etf.aor.gui;

import javax.swing.JFrame;

/**
 *
 * @author MB
 */
public class RegisterDialog extends javax.swing.JDialog {

    /** Creates new form RegisterDialog */
    public RegisterDialog(JFrame parent) {
        super(parent, true);
        initComponents();
        setResizable(false);
    }

    public RegisterDialog(JFrame parent, String pc, String a, String b, String ir1, String ir2, String ir3, String ir4, String mar, String mbr,
                            String x, String y, String ivtp, String br, String ax, String bx, String cx, String dx, String si,
                                String di, String sp, String bp, String sbus, String dbus, String systemABUS, String systemDBUS, String psw) {
        this(parent);
        pcTextField.setText(pc);
        aTextField.setText(a);
        bTextField.setText(b);
        ir1TextField.setText(ir1);
        ir2TextField.setText(ir2);
        ir3TextField.setText(ir3);
        ir4TextField.setText(ir4);
        marTextField.setText(mar);
        mbrTextField.setText(mbr);
        xTextField.setText(x);
        yTextField.setText(y);
        ivtpTextField.setText(ivtp);
        axTextField.setText(ax);
        bxTextField.setText(bx);
        cxTextField.setText(cx);
        dxTextField.setText(dx);
        siTextField.setText(si);
        diTextField.setText(di);
        spTextField.setText(sp);
        bpTextField.setText(bp);
        sbusTextField.setText(sbus);
        dbusTextField.setText(dbus);
        systemABUSTextField.setText(systemABUS);
        systemDBUSTextField.setText(systemDBUS);
        pswTextField.setText(psw);

    }

    public void refreshValues (String pc, String a, String b, String ir1, String ir2, String ir3, String ir4, String mar, String mbr,
                                String x, String y, String ivtp, String br, String ax, String bx, String cx, String dx, String si,
                                String di, String sp, String bp, String sbus, String dbus, String systemABUS, String systemDBUS, String psw) {

        pcTextField.setText(pc);
        aTextField.setText(a);
        bTextField.setText(b);
        ir1TextField.setText(ir1);
        ir2TextField.setText(ir2);
        ir3TextField.setText(ir3);
        ir4TextField.setText(ir4);
        marTextField.setText(mar);
        mbrTextField.setText(mbr);
        xTextField.setText(x);
        yTextField.setText(y);
        ivtpTextField.setText(ivtp);
        axTextField.setText(ax);
        bxTextField.setText(bx);
        cxTextField.setText(cx);
        dxTextField.setText(dx);
        siTextField.setText(si);
        diTextField.setText(di);
        spTextField.setText(sp);
        bpTextField.setText(bp);
        sbusTextField.setText(sbus);
        dbusTextField.setText(dbus);
        systemABUSTextField.setText(systemABUS);
        systemDBUSTextField.setText(systemDBUS);
        pswTextField.setText(psw);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        axTextField = new javax.swing.JTextField();
        bxTextField = new javax.swing.JTextField();
        cxTextField = new javax.swing.JTextField();
        dxTextField = new javax.swing.JTextField();
        siTextField = new javax.swing.JTextField();
        diTextField = new javax.swing.JTextField();
        spTextField = new javax.swing.JTextField();
        bpTextField = new javax.swing.JTextField();
        pcTextField = new javax.swing.JTextField();
        ir1TextField = new javax.swing.JTextField();
        ir2TextField = new javax.swing.JTextField();
        marTextField = new javax.swing.JTextField();
        ivtpTextField = new javax.swing.JTextField();
        mbrTextField = new javax.swing.JTextField();
        ir3TextField = new javax.swing.JTextField();
        ir4TextField = new javax.swing.JTextField();
        xTextField = new javax.swing.JTextField();
        yTextField = new javax.swing.JTextField();
        aTextField = new javax.swing.JTextField();
        bTextField = new javax.swing.JTextField();
        pswTextField = new javax.swing.JTextField();
        imrTextField = new javax.swing.JTextField();
        sbusTextField = new javax.swing.JTextField();
        dbusTextField = new javax.swing.JTextField();
        systemABUSTextField = new javax.swing.JTextField();
        systemDBUSTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        okButton = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setTitle("RegisterDialog");
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(688, 285));
        setName(""); // NOI18N

        jLabel1.setText("AX");

        jLabel2.setText("BX");

        jLabel3.setText("CX");

        jLabel4.setText("DX");

        jLabel5.setText("SI");

        jLabel6.setText("DI");

        jLabel7.setText("SP");

        jLabel8.setText("BP");

        jLabel9.setText("PC");

        jLabel10.setText("IR1");

        jLabel11.setText("IR2");

        jLabel12.setText("MAR");

        jLabel13.setText("MBR");

        jLabel14.setText("IVTP");

        jLabel15.setText("IR3");

        jLabel16.setText("IR4");

        jLabel17.setText("X");

        jLabel18.setText("Y");

        jLabel19.setText("A");

        jLabel20.setText("B");

        jLabel21.setText("PSW");

        jLabel22.setText("IMR");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel23.setText("CPU");

        jLabel24.setText("sBUS");

        jLabel25.setText("dBUS");

        jLabel26.setText("ABUS");

        jLabel27.setText("DBUS");

        jLabel28.setText("bin.");

        jLabel29.setText("bin.");

        axTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        axTextField.setText("0000");
        axTextField.setFocusable(false);
        axTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        axTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        bxTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bxTextField.setText("0000");
        bxTextField.setFocusable(false);
        bxTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        bxTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        cxTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cxTextField.setText("0000");
        cxTextField.setFocusable(false);
        cxTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        cxTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        dxTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dxTextField.setText("0000");
        dxTextField.setFocusable(false);
        dxTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        dxTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        siTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        siTextField.setText("0000");
        siTextField.setFocusable(false);
        siTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        siTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        diTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        diTextField.setText("0000");
        diTextField.setFocusable(false);
        diTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        diTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        spTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        spTextField.setText("0000");
        spTextField.setFocusable(false);
        spTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        spTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        bpTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bpTextField.setText("0000");
        bpTextField.setFocusable(false);
        bpTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        bpTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        pcTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pcTextField.setText("0000");
        pcTextField.setFocusable(false);
        pcTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        pcTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        ir1TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ir1TextField.setText("0000");
        ir1TextField.setFocusable(false);
        ir1TextField.setMaximumSize(new java.awt.Dimension(30, 20));
        ir1TextField.setMinimumSize(new java.awt.Dimension(30, 20));

        ir2TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ir2TextField.setText("0000");
        ir2TextField.setFocusable(false);
        ir2TextField.setMaximumSize(new java.awt.Dimension(30, 20));
        ir2TextField.setMinimumSize(new java.awt.Dimension(30, 20));

        marTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        marTextField.setText("0000");
        marTextField.setFocusable(false);
        marTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        marTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        ivtpTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ivtpTextField.setText("0000");
        ivtpTextField.setFocusable(false);
        ivtpTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        ivtpTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        mbrTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mbrTextField.setText("0000");
        mbrTextField.setFocusable(false);
        mbrTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        mbrTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        ir3TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ir3TextField.setText("0000");
        ir3TextField.setFocusable(false);
        ir3TextField.setMaximumSize(new java.awt.Dimension(30, 20));
        ir3TextField.setMinimumSize(new java.awt.Dimension(30, 20));

        ir4TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ir4TextField.setText("0000");
        ir4TextField.setFocusable(false);
        ir4TextField.setMaximumSize(new java.awt.Dimension(30, 20));
        ir4TextField.setMinimumSize(new java.awt.Dimension(30, 20));

        xTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xTextField.setText("0000");
        xTextField.setFocusable(false);
        xTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        xTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        yTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yTextField.setText("0000");
        yTextField.setFocusable(false);
        yTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        yTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        aTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aTextField.setText("0000");
        aTextField.setFocusable(false);
        aTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        aTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        bTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bTextField.setText("0000");
        bTextField.setFocusable(false);
        bTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        bTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        pswTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pswTextField.setText("0000000000000000");
        pswTextField.setFocusable(false);
        pswTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        pswTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        imrTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        imrTextField.setText("0000");
        imrTextField.setFocusable(false);
        imrTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        imrTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        sbusTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sbusTextField.setText("0000");
        sbusTextField.setFocusable(false);
        sbusTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        sbusTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        dbusTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dbusTextField.setText("0000");
        dbusTextField.setFocusable(false);
        dbusTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        dbusTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        systemABUSTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        systemABUSTextField.setText("0000");
        systemABUSTextField.setFocusable(false);
        systemABUSTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        systemABUSTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        systemDBUSTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        systemDBUSTextField.setText("0000");
        systemDBUSTextField.setFocusable(false);
        systemDBUSTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        systemDBUSTextField.setMinimumSize(new java.awt.Dimension(30, 20));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel30.setText("interne \nmagistrale");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel31.setText("sistemske magistrale");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(dxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(cxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(bxTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                            .addComponent(axTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(siTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(diTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(spTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(bpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ivtpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pcTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                            .addComponent(mbrTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                            .addComponent(marTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(imrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(18, 18, 18)
                                        .addComponent(pswTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ir1TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(ir2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(ir3TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(ir4TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(xTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(yTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(aTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(bTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                        .addComponent(jLabel24)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dbusTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(sbusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel26)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(systemDBUSTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(systemABUSTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(marTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(mbrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(siTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(diTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(spTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14)
                                        .addComponent(ivtpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(axTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(bxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(dxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(pswTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(imrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel29)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel24)
                                        .addComponent(sbusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel25)
                                        .addComponent(dbusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel26)
                                        .addComponent(systemABUSTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel27)
                                        .addComponent(systemDBUSTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(okButton))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(xTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(yTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(ir1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(ir2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(ir3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(ir4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(71, 71, 71)
                            .addComponent(jLabel23))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aTextField;
    private javax.swing.JTextField axTextField;
    private javax.swing.JTextField bTextField;
    private javax.swing.JTextField bpTextField;
    private javax.swing.JTextField bxTextField;
    private javax.swing.JTextField cxTextField;
    private javax.swing.JTextField dbusTextField;
    private javax.swing.JTextField diTextField;
    private javax.swing.JTextField dxTextField;
    private javax.swing.JTextField imrTextField;
    private javax.swing.JTextField ir1TextField;
    private javax.swing.JTextField ir2TextField;
    private javax.swing.JTextField ir3TextField;
    private javax.swing.JTextField ir4TextField;
    private javax.swing.JTextField ivtpTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField marTextField;
    private javax.swing.JTextField mbrTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField pcTextField;
    private javax.swing.JTextField pswTextField;
    private javax.swing.JTextField sbusTextField;
    private javax.swing.JTextField siTextField;
    private javax.swing.JTextField spTextField;
    private javax.swing.JTextField systemABUSTextField;
    private javax.swing.JTextField systemDBUSTextField;
    private javax.swing.JTextField xTextField;
    private javax.swing.JTextField yTextField;
    // End of variables declaration//GEN-END:variables

}
